// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGNVIkcwA-3MNpjOGZi7MbMb-DYrHZUDs',
    appId: '1:32860798291:web:b5d37689848cb465f035a6',
    messagingSenderId: '32860798291',
    projectId: 'divyanga',
    authDomain: 'divyanga.firebaseapp.com',
    databaseURL: 'https://divyanga-default-rtdb.firebaseio.com',
    storageBucket: 'divyanga.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN-MBbtZQZboew-xiWjV64ez2sIQY_sy8',
    appId: '1:32860798291:android:f84695153aa326b0f035a6',
    messagingSenderId: '32860798291',
    projectId: 'divyanga',
    databaseURL: 'https://divyanga-default-rtdb.firebaseio.com',
    storageBucket: 'divyanga.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmgbf7w3QIR13CfXmt4cZWI9k4P-PXvZw',
    appId: '1:32860798291:ios:036ab7bd73209cbef035a6',
    messagingSenderId: '32860798291',
    projectId: 'divyanga',
    databaseURL: 'https://divyanga-default-rtdb.firebaseio.com',
    storageBucket: 'divyanga.appspot.com',
    iosBundleId: 'com.example.divyanga',
  );
}
